server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bet-service
    username: postgres
    password: ${DBPASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update