server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bet-service
    username: postgres
    password: ${DBPASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bet-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.commons.MatchFinishedEvent

match:
  service:
    url: http://localhost:8093