server:
  port: 8093

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/match-service
    username: postgres
    password: ${DBPASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
football:
  api:
    url: ${FOOTBALL_API_URL}
    key: ${FOOTBALL_API_KEY}

